### ISSUE TITLE
Cannot push to portainer  since version 1.0.0

### ISSUE THREAD

**Issue by ghost** [LGinC/portainer-stack-deploy#3]
Since version 1.0.0 when push to Portainer my stack this error appears : 

My config : 
```
- name: deploy to portainer
  uses: LGinC/portainer-stack-deploy@latest
  with:
       serverurl: ****
       username: ****
       password: ****
       endpointId: 1
       stackname: ****
       docker_compose: ****
```

> /usr/bin/docker run --name ghcriolgincportainerstackdeploy_ea0ef7 --label 7db2d7 --workdir /github/workspace --rm -e SHA -e INPUT_SERVERURL -e INPUT_REPO_USERNAME -e INPUT_REPO_PASSWORD -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_ENDPOINTID -e INPUT_STACKNAME -e INPUT_DOCKER_COMPOSE -e INPUT_ACCESS_TOKEN -e INPUT_IMAGENAMES -e INPUT_ENV -e INPUT_VARIABLES -e INPUT_DOCKER_COMPOSE_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/v2/v2":"/github/workspace" ghcr.io/lginc/portainer-stack-deploy
> WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
> standard_init_linux.go:228: exec user process caused: exec format error

When downgrade to 0.3.1 this error disappears and deploy run as normally.

My config : 
```
- name: deploy to portainer
  uses: LGinC/portainer-stack-deploy@0.3.1
  with:
       serverurl: ****
       username: ****
       password: ****
       endpointId: 1
       registry: ghcr.io
       stackname: ****
       docker_compose: ****
```

In 0.3.1 I add "registry" entry -> in 1.0.0 since this enter is deprecated I don't use it.

Do you have an solution for this error ?

**Comment by LGinC** [comment]
don't need parameter `registry` anymore.
if you want to pull image, just fill `imagenames`
```yaml
- name: deploy to portainer
  uses: LGinC/portainer-stack-deploy@master
  with:
       serverurl: ****
       username: ****
       password: ****
       imagenames: 
        - ghcr.io/xxx/xx:xx
       stackname: ****
       docker_compose: ****
```

if your registry is private, then you need [add registry authentication to portainer](https://docs.portainer.io/v/ce-2.11/admin/registries/add)

if your image tag will change in every build, you can use [variables](https://github.com/LGinC/portainer-stack-deploy#variables) to replace tag, not pull image, because portainer will pull it auto when update stack or create stack.

and endpoint default value is 1, so you can remove it.
username and password maybe not safe enough, and you can use [access_token](https://github.com/LGinC/portainer-stack-deploy#access_token).

there is some [example](https://github.com/LGinC/portainer-stack-deploy#example-usage)

**Comment by ghost** [comment]
So I do changes for match with your advice but I have a new error.
I also create in portainer my access_token and save it as secret in my github repo as PORTAINER_ACCESS. 
HTTPS is enable in portainer.

My new config : 
```
- name: deploy to portainer
   uses: LGinC/portainer-stack-deploy@1.0
   with:
      serverurl: https://*****
      access_token: ${{secrets.PORTAINER_ACCESS}}
      repo_username: ${{ github.actor }}
      repo_password: ${{secrets.REGISTRY_PAT}}
      stackname: *****
      docker_compose: |
        version: "3.4"
        services:
          ################################ APP ###################################
          app:
            image: ghcr.io/****/****/****:${{ steps.short-sha.outputs.sha }}
            ....
```

I don't reference `imagenames` attribute because I have some image and when I put more than one image it doesn't work.


My error : 

> /usr/bin/docker run --name ghcriolgincportainerstackdeploy_b42dba --label 7db2d7 --workdir /github/workspace --rm -e SHA -e INPUT_SERVERURL -e INPUT_ACCESS_TOKEN -e INPUT_REPO_USERNAME -e INPUT_REPO_PASSWORD -e INPUT_STACKNAME -e INPUT_DOCKER_COMPOSE -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_ENDPOINTID -e INPUT_IMAGENAMES -e INPUT_ENV -e INPUT_VARIABLES -e INPUT_DOCKER_COMPOSE_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/v2/v2":"/github/workspace" ghcr.io/lginc/portainer-stack-deploy
> Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("*****")), port: None, path: "/api/stacks", query: Some("filters={%22EndpointID%22:1,%22IncludeOrphanedStacks%22:true}"), fragment: None }, source: hyper::Error(Connect, "invalid URL, scheme is not http") }
